Repository lirantal/is-website-vulnerable, pull requests merged in 2019-10, with the labels that each got.

#9 doc(readme): Fix small typo
  README.md
Labels: bug, hacktoberfest

#15 fix(linux): chrome flags to support linux execution
  src/Audit.js
Labels: bug

#16 feat(debug): enable debugging
  bin/is-website-vulnerable.js
  package.json
  src/Audit.js
Labels: enhancement

#17 feat(node): support node versions < 10 for lighthouse
  src/Audit.js
Labels: bug

#10 feat(json): prints result as JSON if --json flag is passed alongside URL
  .gitignore
  README.md
  __tests__/RenderJson.test.js
  bin/is-website-vulnerable.js
  index.js
  package.json
  src/RenderConsole.js
  src/RenderJson.js
  yarn.lock
Labels: enhancement, hacktoberfest

#13 feat(CLI): Add a progress spinner
  package.json
  src/Audit.js
Labels: enhancement

#19 Hide the progress-bar if --json is provided
  bin/is-website-vulnerable.js
  src/Audit.js
  yarn.lock
Labels: bug

#24 docs: remove outdated commit script, a hook is used now
  CONTRIBUTING.md
Labels: documentation

#28 fix(deps): pin all deps and enforce them with shrinkwrap
  npm-shrinkwrap.json
  package.json
  yarn.lock
Labels: enhancement

#21 feat(jslib): print library information if --js-lib flag is passed
  __tests__/RenderConsole.test.js
  __tests__/fixtures/library-empty.json
  __tests__/fixtures/multiple-libraries.json
  bin/is-website-vulnerable.js
  src/RenderConsole.js
Labels: enhancement

#29 fix(libs): fix the libraries output style
  src/RenderConsole.js
Labels: bug

#25 ci: migrate to GitHub Actions
  .github/workflows/main.yml
  .travis.yml
  README.md
Labels: build, enhancement

#39 fix(release): update semantic release to support github actions
  npm-shrinkwrap.json
  package.json
  yarn.lock
Labels: bug

#41 chore: update CI for release step
  .github/workflows/main.yml
Labels: enhancement

#40 fix: lighthouseSettings misspelled
  src/Audit.js
Labels: bug

#38 feat(lib): Trim snyk url from utm_* query params on the results
  .gitignore
  __tests__/Utils.test.js
  src/RenderConsole.js
  src/RenderJson.js
  src/Utils.js
Labels: enhancement, hacktoberfest

#42 fix(readme): update device type flags
  README.md
Labels: documentation, hacktoberfest

#31 feat(libs): print library information in json rendering
  __tests__/RenderJson.test.js
  bin/is-website-vulnerable.js
  src/RenderConsole.js
  src/RenderJson.js
Labels: enhancement
