Repository lirantal/is-website-vulnerable, pull requests merged in 2019-12, with the labels that each got.

#47 fixes (#22): introduce chromePath parameter to use custom chrome path
  .gitignore
  README.md
  __tests__/Audit.test.js
  bin/is-website-vulnerable.js
  src/Audit.js
Labels: enhancement

#51 docs(browser-version): added a warning about the version requirement
  README.md
Labels: documentation

#57 containerization of is-website-vulnerable and README updated
  Dockerfile
  README.md
Labels: documentation, enhancement

#58 Gracefully handle missing URL argument
  README.md
  __tests__/Audit.test.js
  bin/is-website-vulnerable.js
  npm-shrinkwrap.json
  package.json
  src/Audit.js
Labels: enhancement
